[profile.default]
via_ir = true
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
zircuit-testnet="https://garfield-testnet.zircuit.com/"

[etherscan]
zircuit-testnet = { key = "${ZIRCUIT_TESTNET_API_KEY}", url = "https://explorer.garfield-testnet.zircuit.com/api/contractVerifyHardhat" }